# Use postgres/example user/password credentials
version: '3.3'
services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: {PG_USER}
      POSTGRES_PASSWORD: {PG_PASS}
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_DEFAULT_EMAIL: {PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: {PGADMIN_DEFAULT_PASS}
    ports:
      - "8088:80"
    networks:
      - postgres-compose-network
    depends_on:
      - postgres_db
networks:
  postgres-compose-network:
    driver: bridge